namespace: fleet-mc-manifest-example
targetCustomizations:
- name: c-hr5b4
  clusterSelector:
    matchLabels:
      env: gcr
  yaml:
    overlays:
    # Refers to overlays/noreplication folder
    - noreplication

- name: local
  clusterSelector: {}
  yaml:
    overlays:
    # Refers to overlays/scale3 folder
    - scale3

- name: prod
  clusterSelector:
    matchLabels:
      env: prod
  yaml:
    # Refers to overlays/servicelb, scale3 folders
    overlays:
    - servicelb
    - scale3
